swetlana_p_homework_4_done
eugene-okulik/Swetlana pull request #3
Opened 2024-12-17 16:12 UTC by LanaPush

2024-12-18 07:35 UTC, eugene-okulik requested changes
Всё отлично, но проверку на внимательность не прошла )))

2024-12-18 07:35 UTC, eugene-okulik commented on homework/swetlana_pushnitsa/homework_4/task_1.py
> +my_dict["dict"]["i am a tuple"] = 6
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-12-18 08:59 UTC, LanaPush commented on homework/swetlana_pushnitsa/homework_4/task_1.py
> +my_dict["dict"]["i am a tuple"] = 6
блииин :)) Переделаю, спасибо!

2024-12-19 06:44 UTC, eugene-okulik approved these changes

2024-12-19 06:44 UTC, merged